version: '3'
services:
  database:
    image: postgres:latest

  redis:
    image: redis:latest

  web:
    build: .
    env_file:
      - .env
    environment:
      CREATE_DATABASE_URL: postgres://postgres@database/postgres?pool=20
      DATABASE_URL: postgres://postgres@database/pr_checker_dev?pool=20
      SIDEKIQ_REDIS_URL: redis://redis:6379/
    ports:
      - '9292:80'
    depends_on:
      - database
      - redis

  sidekiq:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres@database/pr_checker_dev?pool=20
      SIDEKIQ_REDIS_URL: redis://redis:6379/
    command: bundle exec sidekiq -r ./environment.rb
    restart: always
    depends_on:
      - database
      - redis
