version: '3'
services:
  database:
    image: mongo:3.2
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  redis:
    image: redis:latest

  web:
    # tty: true # Enables debugging capabilities when attached to this container.
    build: .
    # volumes:
    #   - .:/app
    env_file:
      - .env
    environment:
      DATABASE_HOST: database
      SIDEKIQ_REDIS_URL: redis://redis:6379/
    ports:
      - '9292:80'
    depends_on:
      - database
      - redis

  sidekiq:
    # tty: true # Enables debugging capabilities when attached to this container.
    build: .
    env_file:
      - .env
    environment:
      DATABASE_HOST: database
      SIDEKIQ_REDIS_URL: redis://redis:6379/
    command: bundle exec sidekiq -r ./environment.rb -L STDOUT
    restart: always
    depends_on:
      - database
      - redis
