default: &default
  # adapter: sqlite3
  # database: db/data.sqlite3
  # database: :memory:

  adapter: postgresql

  pool: 20
  timeout: 5000
  # username: "postgres",
  # password: ""
  # encoding: "unicode",
  # encoding: utf-8

  host: 127.0.0.1

development:
  <<: *default
  database: pr_checker_dev

test:
  <<: *default
  database: pr_checker_test

production:
  <<: *default
  database: pr_checker
